version: '3.8'

services:
    dev:
        container_name: homelab-pi-stats
        image: punparin/homelab-pi-stats:local
        env_file:
            - .env
        ports:
            - 3000:3000
        restart: unless-stopped